export const property = [
  {
    id: 1,
    popular: false,
    name: "Beverly Hills",
    description: "Magnifcation bungalow close to the beach",
    type: "bungalow",
    cost: 6000,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2023-03-01",
    address: {
      street: "26 Green",
      cityCountry: "New York, USA",
    },
  },
  {
    id: 2,
    popular: true,
    name: "The Willow",
    description: "Magnifcation bungalow close to the beach",
    type: "cottage",
    cost: 2200,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2023-04-11",
    address: {
      street: "26 Green",
      cityCountry: "Texas, USA",
    },
  },
  {
    id: 3,

    popular: false,
    name: "The Barn",
    description: "Magnifcation bungalow close to the beach",
    type: "cottage",
    cost: 1800,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2023-02-01",
    address: {
      street: "26 Green",
      cityCountry: "New York, USA",
    },
  },
  {
    id: 4,

    popular: true,
    name: "Mulburry",
    description: "Magnifcation bungalow close to the beach",
    type: "villa",
    cost: 2000,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2023-02-01",
    address: {
      street: "26 Green",
      cityCountry: "New York, USA",
    },
  },

  {
    id: 5,

    popular: true,
    name: "Greenacres",
    description: "Magnifcation bungalow close to the beach",
    type: "flat",
    cost: 2000,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2023-02-01",
    address: {
      street: "26 Green",
      cityCountry: "Utah, USA",
    },
  },
  {
    id: 6,

    popular: false,
    name: "Beverly Hills Bungalow",
    description: "Magnifcation bungalow close to the beach",
    type: "bungalow",
    cost: 2000,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2023-02-01",
    address: {
      street: "26 Green",
      cityCountry: "New York, USA",
    },
  },
  {
    id: 7,

    popular: true,
    name: "Woodside",
    description: "Magnifcation bungalow close to the beach",
    type: "cottage",
    cost: 2500,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2023-12-21",
    address: {
      street: "26 Green",
      cityCountry: "Utah, USA",
    },
  },
  {
    id: 8,

    popular: false,
    name: "La Scala",
    description: "Magnifcation bungalow close to the beach",
    type: "flat",
    cost: 2000,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2023-02-01",
    address: {
      street: "26 Green",
      cityCountry: "California, USA",
    },
  },
  {
    id: 9,

    popular: true,
    name: "Tannery Gargens",
    description: "Magnifcation bungalow close to the beach",
    type: "bungalow",
    cost: 2000,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2022-12-01",
    address: {
      street: "26 Green",
      cityCountry: "Texas, USA",
    },
  },
  {
    id: 10,

    popular: true,
    name: "Meadow View",
    description: "Magnifcation bungalow close to the beach",
    type: "bungalow",
    cost: 2000,
    beds: 3,
    bath: 5,
    area: 225,
    moveDate: "2023-02-01",
    address: {
      street: "26 Green",
      cityCountry: "California, USA",
    },
  },
];
